import { Request, Response, NextFunction } from 'express';
import crypto from 'crypto';
import jwt from 'jsonwebtoken';
import prisma from '../../config/database';
import { env } from '../../config/env';
import { issueClientCert } from '../../services/ca.service';
import { 
  getAgentSocket, 
  requestPortScan, 
  terminateAgent,
  listProjectFiles,
  readProjectFile,
  writeProjectFile,
  deleteProjectFile,
  copyProjectFile,
  moveProjectFile
} from '../../services/agent-ws.service';
import { getRedisClient } from '../../config/redis';

// ── POST /api/v1/agent/enroll ─────────────────────────────────────────────────
/**
 * Validates the provisioning token, issues mTLS client certificates,
 * and returns them in a JSON payload for the install script.
 *
 * The provisioning token is a JWT with claim { nodeId, purpose: "enroll" }
 * generated by createNode() below.
 */
export async function enrollAgent(req: Request, res: Response, next: NextFunction) {
  try {
    const authHeader = req.headers['authorization'] ?? '';
    const raw = authHeader.startsWith('Bearer ') ? authHeader.slice(7) : '';
    if (!raw) {
      res.status(401).json({ status: 'error', message: 'Enrollment token required.' });
      return;
    }

    let decoded: any;
    try {
      decoded = jwt.verify(raw, env.JWT_SECRET);
    } catch {
      res.status(401).json({ status: 'error', message: 'Invalid or expired enrollment token.' });
      return;
    }

    if (decoded.purpose !== 'enroll' || !decoded.nodeId) {
      res.status(401).json({ status: 'error', message: 'Token is not a valid enrollment token.' });
      return;
    }

    const node = await prisma.node.findUnique({ where: { id: decoded.nodeId } });
    if (!node) {
      res.status(404).json({ status: 'error', message: 'Node not found.' });
      return;
    }

    // Issue a long-lived JWT the agent will use for all future WS connections.
    // The WS server authenticates agents with jwt.verify(), so we need a proper
    // JWT here — the raw node.token (random hex) cannot be verified that way.
    const agentToken = jwt.sign(
      { nodeId: node.id },
      env.JWT_SECRET,
      // No expiry — the token is tied to this node and revoked by deleting the node.
    );

    res.json({ status: 'success', data: { nodeToken: agentToken } });
  } catch (error) {
    next(error);
  }
}

// ── GET /api/v1/agent/nodes ───────────────────────────────────────────────────
export async function listNodes(_req: Request, res: Response, next: NextFunction) {
  try {
    const nodes = await prisma.node.findMany({ orderBy: { createdAt: 'desc' } });
    res.json({ status: 'success', data: { nodes } });
  } catch (error) {
    next(error);
  }
}

// ── POST /api/v1/agent/nodes ──────────────────────────────────────────────────
/**
 * Registers a new node and returns a short-lived JWT enrollment token
 * that the install script will use to call /enroll.
 */
export async function createNode(req: Request, res: Response, next: NextFunction) {
  try {
    const { name } = req.body as { name?: string };
    if (!name || name.trim().length === 0) {
      res.status(400).json({ status: 'error', message: '"name" is required.' });
      return;
    }

    // Permanent token stored in DB — used to match the node on reconnect
    const persistentToken = crypto.randomBytes(32).toString('hex');

    const node = await prisma.node.create({
      data: {
        name:   name.trim(),
        os:     'unknown',
        arch:   'unknown',
        token:  persistentToken,
        status: 'OFFLINE',
      },
    });

    // Short-lived JWT for the install script (1 hour)
    const enrollToken = jwt.sign(
      { nodeId: node.id, purpose: 'enroll' },
      env.JWT_SECRET,
      { expiresIn: '1h' },
    );

    res.status(201).json({
      status: 'success',
      data: { node, enrollToken },
    });
  } catch (error) {
    next(error);
  }
}

// ── DELETE /api/v1/agent/nodes/:id ───────────────────────────────────────────
export async function deleteNode(req: Request<{ id: string }>, res: Response, next: NextFunction) {
  try {
    const { id } = req.params;
    const ws = getAgentSocket(id);
    if (ws) ws.close(1000, 'Node deleted');

    await prisma.node.delete({ where: { id } });
    res.json({ status: 'success', message: 'Node deleted.' });
  } catch (error) {
    next(error);
  }
}

// ── POST /api/v1/agent/nodes/:id/command ─────────────────────────────────────
/**
 * Sends a JSON command to a connected agent (e.g. stream_logs, update).
 */
export async function sendCommand(
  req: Request<{ id: string }>,
  res: Response,
  next: NextFunction,
) {
  try {
    const { id } = req.params;
    const ws = getAgentSocket(id);

    if (!ws || ws.readyState !== ws.OPEN) {
      res.status(409).json({ status: 'error', message: 'Agent is not connected.' });
      return;
    }

    ws.send(JSON.stringify(req.body));
    res.json({ status: 'success', message: 'Command dispatched.' });
  } catch (error) {
    next(error);
  }
}

// ── GET /api/v1/agent/nodes/:id/telemetry ────────────────────────────────────
/**
 * Fetches the historical telemetry data (last 100 entries) from Redis.
 */
export async function getNodeTelemetry(req: Request<{ id: string }>, res: Response, next: NextFunction) {
  try {
    const { id } = req.params;
    const redis = await getRedisClient();
    const key = `node:${id}:telemetry`;
    
    // Fetch the 100 entries. They are stored as strings.
    const rawData = await redis.lRange(key, 0, 99);
    
    // Parse strings and return in chronological order (LPUSH stores newest at index 0, so we reverse it)
    const telemetry = rawData.map(str => {
      try { return JSON.parse(str); } catch { return null; }
    }).filter(Boolean).reverse();

    res.json({ status: 'success', data: { telemetry } });
  } catch (error) {
    next(error);
  }
}

// ── GET /api/v1/agent/nodes/:id/scan-ports ──────────────────────────────────
/**
 * Requests a real-time port scan from a connected agent.
 */
export async function scanNodePorts(req: Request<{ id: string }>, res: Response, next: NextFunction) {
  try {
    const { id } = req.params;
    const ports = await requestPortScan(id);
    res.json({ status: 'success', data: { ports } });
  } catch (error) {
    // If agent is offline or timeout occurs
    res.status(502).json({ status: 'error', message: error instanceof Error ? error.message : 'Port scan failed' });
  }
}

// ── POST /api/v1/agent/nodes/:id/terminate ──────────────────────────────────
export async function terminateNodeAgent(req: Request<{ id: string }>, res: Response, next: NextFunction) {
  try {
    const { id } = req.params;
    terminateAgent(id);
    await prisma.node.update({ where: { id }, data: { status: 'OFFLINE' } });
    res.json({ status: 'success', message: 'Termination command sent.' });
  } catch (error) {
    next(error);
  }
}

// ── GET /api/v1/agent/nodes/:id/files ────────────────────────────────────────
export async function listNodeFiles(req: Request<{ id: string }>, res: Response, next: NextFunction) {
  try {
    const { id } = req.params;
    const filePath = (req.query.path as string) ?? '';
    const entries = await listProjectFiles(id, '', filePath);
    res.json({ status: 'success', data: { entries } });
  } catch (error) {
    next(error);
  }
}

// ── GET /api/v1/agent/nodes/:id/files/read ───────────────────────────────────
export async function readNodeFile(req: Request<{ id: string }>, res: Response, next: NextFunction) {
  try {
    const { id } = req.params;
    const filePath = (req.query.path as string) ?? '';
    if (!filePath) {
      res.status(400).json({ status: 'error', message: 'path query param required' });
      return;
    }
    const content = await readProjectFile(id, '', filePath);
    res.json({ status: 'success', data: { content } });
  } catch (error) {
    next(error);
  }
}

// ── POST /api/v1/agent/nodes/:id/files/write ──────────────────────────────────
export async function writeNodeFile(req: Request<{ id: string }>, res: Response, next: NextFunction) {
  try {
    const { id } = req.params;
    const { path: filePath, content } = req.body;
    if (!filePath || content === undefined) {
      res.status(400).json({ status: 'error', message: 'path and content are required' });
      return;
    }
    await writeProjectFile(id, '', filePath, content);
    res.json({ status: 'success', message: 'File saved' });
  } catch (error) {
    next(error);
  }
}

// ── DELETE /api/v1/agent/nodes/:id/files ──────────────────────────────────────
export async function deleteNodeFile(req: Request<{ id: string }>, res: Response, next: NextFunction) {
  try {
    const { id } = req.params;
    const filePath = (req.query.path as string) ?? '';
    if (!filePath) {
      res.status(400).json({ status: 'error', message: 'path query param required' });
      return;
    }
    await deleteProjectFile(id, '', filePath);
    res.json({ status: 'success', message: 'File deleted' });
  } catch (error) {
    next(error);
  }
}

// ── POST /api/v1/agent/nodes/:id/files/copy ───────────────────────────────────
export async function copyNodeFile(req: Request<{ id: string }>, res: Response, next: NextFunction) {
  try {
    const { id } = req.params;
    const { path: filePath, dest: destPath } = req.body;
    if (!filePath || !destPath) {
      res.status(400).json({ status: 'error', message: 'path and dest are required' });
      return;
    }
    await copyProjectFile(id, 'host', filePath, destPath);
    res.json({ status: 'success', message: 'File copied' });
  } catch (error) {
    next(error);
  }
}

// ── POST /api/v1/agent/nodes/:id/files/move ───────────────────────────────────
export async function moveNodeFile(req: Request<{ id: string }>, res: Response, next: NextFunction) {
  try {
    const { id } = req.params;
    const { path: filePath, dest: destPath } = req.body;
    if (!filePath || !destPath) {
      res.status(400).json({ status: 'error', message: 'path and dest are required' });
      return;
    }
    await moveProjectFile(id, 'host', filePath, destPath);
    res.json({ status: 'success', message: 'File moved' });
  } catch (error) {
    next(error);
  }
}
