import { Request, Response, NextFunction } from 'express';
import crypto from 'crypto';
import jwt from 'jsonwebtoken';
import prisma from '../../config/database';
import { env } from '../../config/env';
import { issueClientCert } from '../../services/ca.service';
import { getAgentSocket } from '../../services/agent-ws.service';

// ── POST /api/v1/agent/enroll ─────────────────────────────────────────────────
/**
 * Validates the provisioning token, issues mTLS client certificates,
 * and returns them in a JSON payload for the install script.
 *
 * The provisioning token is a JWT with claim { nodeId, purpose: "enroll" }
 * generated by createNode() below.
 */
export async function enrollAgent(req: Request, res: Response, next: NextFunction) {
  try {
    const authHeader = req.headers['authorization'] ?? '';
    const raw = authHeader.startsWith('Bearer ') ? authHeader.slice(7) : '';
    if (!raw) {
      res.status(401).json({ status: 'error', message: 'Enrollment token required.' });
      return;
    }

    let decoded: any;
    try {
      decoded = jwt.verify(raw, env.JWT_SECRET);
    } catch {
      res.status(401).json({ status: 'error', message: 'Invalid or expired enrollment token.' });
      return;
    }

    if (decoded.purpose !== 'enroll' || !decoded.nodeId) {
      res.status(401).json({ status: 'error', message: 'Token is not a valid enrollment token.' });
      return;
    }

    const node = await prisma.node.findUnique({ where: { id: decoded.nodeId } });
    if (!node) {
      res.status(404).json({ status: 'error', message: 'Node not found.' });
      return;
    }

    const certs = await issueClientCert(`node-${node.id}`);

    res.json({ status: 'success', data: certs });
  } catch (error) {
    next(error);
  }
}

// ── GET /api/v1/agent/nodes ───────────────────────────────────────────────────
export async function listNodes(_req: Request, res: Response, next: NextFunction) {
  try {
    const nodes = await prisma.node.findMany({ orderBy: { createdAt: 'desc' } });
    res.json({ status: 'success', data: { nodes } });
  } catch (error) {
    next(error);
  }
}

// ── POST /api/v1/agent/nodes ──────────────────────────────────────────────────
/**
 * Registers a new node and returns a short-lived JWT enrollment token
 * that the install script will use to call /enroll.
 */
export async function createNode(req: Request, res: Response, next: NextFunction) {
  try {
    const { name } = req.body as { name?: string };
    if (!name || name.trim().length === 0) {
      res.status(400).json({ status: 'error', message: '"name" is required.' });
      return;
    }

    // Permanent token stored in DB — used to match the node on reconnect
    const persistentToken = crypto.randomBytes(32).toString('hex');

    const node = await prisma.node.create({
      data: {
        name:   name.trim(),
        os:     'unknown',
        arch:   'unknown',
        token:  persistentToken,
        status: 'OFFLINE',
      },
    });

    // Short-lived JWT for the install script (1 hour)
    const enrollToken = jwt.sign(
      { nodeId: node.id, purpose: 'enroll' },
      env.JWT_SECRET,
      { expiresIn: '1h' },
    );

    res.status(201).json({
      status: 'success',
      data: { node, enrollToken },
    });
  } catch (error) {
    next(error);
  }
}

// ── DELETE /api/v1/agent/nodes/:id ───────────────────────────────────────────
export async function deleteNode(req: Request<{ id: string }>, res: Response, next: NextFunction) {
  try {
    const { id } = req.params;
    const ws = getAgentSocket(id);
    if (ws) ws.close(1000, 'Node deleted');

    await prisma.node.delete({ where: { id } });
    res.json({ status: 'success', message: 'Node deleted.' });
  } catch (error) {
    next(error);
  }
}

// ── POST /api/v1/agent/nodes/:id/command ─────────────────────────────────────
/**
 * Sends a JSON command to a connected agent (e.g. stream_logs, update).
 */
export async function sendCommand(
  req: Request<{ id: string }>,
  res: Response,
  next: NextFunction,
) {
  try {
    const { id } = req.params;
    const ws = getAgentSocket(id);

    if (!ws || ws.readyState !== ws.OPEN) {
      res.status(409).json({ status: 'error', message: 'Agent is not connected.' });
      return;
    }

    ws.send(JSON.stringify(req.body));
    res.json({ status: 'success', message: 'Command dispatched.' });
  } catch (error) {
    next(error);
  }
}
